"""convert bonus floats to numeric

Revision ID: 0e5d65e23fa2
Revises: 4b0e84cde0cf
Create Date: 2026-02-17 00:55:35.615409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5d65e23fa2'
down_revision: Union[str, Sequence[str], None] = '4b0e84cde0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonus', 'total_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('bonus', 'points_restants',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('bonus', 'pourcentage_conversion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('bonus', 'valeur_equivalente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonus', 'valeur_equivalente',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bonus', 'pourcentage_conversion',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('bonus', 'points_restants',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('bonus', 'total_points',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
